# Generated by Django 3.1.3 on 2020-11-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('name', models.TextField(verbose_name='имя пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='время получения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сщщбщения',
            },
        ),
    ]
