# Generated by Django 3.1.3 on 2020-11-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201113_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_message', to='bot.profile', verbose_name='Профиль'),
        ),
    ]
